config/routes.rb
Rails.application.routes.draw do
  scope :api, defaults: { format: :json } do
    devise_for :users, controllers: { sessions: :sessions, registrations: :registrations}
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end
  
  get '/api/users/:user_id/posts', to: 'api#user_posts', as: 'api_user_posts'
  get '/api/users/:user_id/posts/:post_id/comments', to: 'api#user_post_comments', as: 'api_posts_comments'
  post '/api/users/:user_id/posts/:post_id/comments', to: 'api#new_comment', as: 'new_post_comment'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :post, class_name: 'Post'
  after_save :update_comments_counter
  after_destroy :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comment.count)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    @comment.user = current_user
    post = Post.find_by(id: params[:post_id])
    @comment.post = post
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to user_post_path(post.user, post)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find_by(id: params[:post_id])
    @comment = @post.comment.find(params[:id])
    @user = current_user
    @post.comments_counter -= 1
    @comment.destroy!
    redirect_to user_post_path(@user.id, @post.id), notice: 'Comment was successfully deleted.'
  end

  private

  def comment_params
    params.permit(:text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_new_comment.html.erb
<h2>Create a new comment</h2>
<%= form_with model: @comment, url: user_post_comments_path(@post.user, @post), method: :post do |form| %>
  <div>
    <%= form.label :text, placeholder: "Leave a comment", class: "small-label" %>
    <%= form.text_area :text, size: "70x5"  %>
  </div>

  <div>
    <%= form.submit "Create Comment", class: "btn" %>
  </div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>