config/routes.rb
Rails.application.routes.draw do
  scope :api, defaults: { format: :json } do
    devise_for :users, controllers: { sessions: :sessions, registrations: :registrations}
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end
  
  get '/api/users/:user_id/posts', to: 'api#user_posts', as: 'api_user_posts'
  get '/api/users/:user_id/posts/:post_id/comments', to: 'api#user_post_comments', as: 'api_posts_comments'
  post '/api/users/:user_id/posts/:post_id/comments', to: 'api#new_comment', as: 'new_post_comment'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post, class_name: 'Post', foreign_key: :user_id, dependent: :destroy
  has_many :comment, class_name: 'Comment', foreign_key: :user_id, dependent: :destroy
  has_many :like, class_name: 'Like', foreign_key: :user_id, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts
    post.includes(:user).order(created_at: :desc).limit(3)
  end

  def generate_jwt
    JWT.encode({ id:, exp: 60.days.from_now.to_i }, Rails.application.secrets.secret_key_base)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_card.html.erb
<section class='user-section-card'>
<div class="user-img">
<%= image_tag('user-img.png',  :width => "100px", :heigth=>"100px") %>
</div>

<div class="user-section-card">
  <div class="user-details">
    <h2> <%= user.name %> </h2>
  </div>
  <div class="user-card">
    <p class="number-posts" >
      Number of posts:<%= user.posts_counter  %>
    </p>  
  </div>
</section>

app/views/users/_users.html.erb
<section class="users">
  <% @users.each do |user| %>
     <%= link_to user do %>
       <%= render partial: "user_card", locals: { user: user } %>
     <% end %>
  <% end %>
</section>

app/views/users/index.html.erb
<%= render 'users'%>

app/views/users/show.html.erb
<section >
<div class='user-section-card'>
       <h2> Would you like to create a post?</h2>
      <%= link_to 'Create new post', new_user_post_path(@user), class: "btn" %>
</div>
<div class="users">
     <%= link_to @user do %>
       <%= render partial: "user_card", locals: { user: @user } %>
     <% end %>
      
      <% @recent_posts.each_with_index do |post,index|  %>
      <section class='user-section-card'>
      <div class="comment-card">
        <div class="user-card__name">
         <h3> Post #<%= index+1 %> </h3>
         <p class="user-bio"><%= post.text %></p>
        </div>
        <div class="comment__like">
        <p class="number-posts">Comments:<%= post.comments_counter %> </p>  
        <p class="number-posts">Likes:<%= post.likes_counter %> </p>  
        </div>
        </div>
      </section>
    <% end %>
  </div>

  <%= link_to 'See all posts', user_posts_path(@user), class: "btn" %>
 <p class="copy-right">© 2022 GitHub, Inc. Terms</p>
</section>