config/routes.rb
Rails.application.routes.draw do
  scope :api, defaults: { format: :json } do
    devise_for :users, controllers: { sessions: :sessions, registrations: :registrations}
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end
  
  get '/api/users/:user_id/posts', to: 'api#user_posts', as: 'api_user_posts'
  get '/api/users/:user_id/posts/:post_id/comments', to: 'api#user_post_comments', as: 'api_posts_comments'
  post '/api/users/:user_id/posts/:post_id/comments', to: 'api#new_comment', as: 'new_post_comment'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :comment, class_name: 'Comment', foreign_key: :post_id, dependent: :destroy
  has_many :like, class_name: 'Like', foreign_key: :post_id, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter
  after_destroy :update_posts_counter

  def update_posts_counter
    user.update(posts_counter: user.post.count)
  end

  def five_recent_comments
    comment.includes(:post).order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @posts = Post.includes(:user).where(user: params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @last_five_comments = @post.five_recent_comments
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to user_post_path(@post.user, @post)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    @user = current_user
    @user.posts_counter -= 1
    @post.destroy!
    redirect_to user_posts_path(@post.user), notice: 'You have successfully delete a post'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_card.html.erb
<section class="user-section-card ">
  <div class="user-section-card comment-owner">
        <% if post.comments_counter == 0 %>
            <p>There is no post does not have any comments</p>
        <% else %>
             <% post.five_recent_comments.each do |comment|  %>
                <ul class="user-details">
                <li ><%= comment.user.name %>: <%= comment.text %>
                <% if can? :destroy, comment  %>
                   <%= button_to 'Delete', user_post_comment_path(post_id: comment.post.id, id: comment.id), method: :delete, class: 'btn btn-danger' %> 
                <% end %>
               </li>               
                </ul>
            <% end %>
        <% end %>
    </div>
</section> 

app/views/posts/_post_cards.html.erb
<section class='user-section-card'>
    <div class="comment-card">
        <div class="user-card__name">
            <h3> <%= post.title %> </h3>
            <p class="user-bio"><%= post.text %></p>
        </div>
        <div class="comment__like">
            <p class="number-posts">Comments:<%= post.recent_comments %> </p>  
            <p class="number-posts">Likes:<%= post.likes_counter %> </p>  
        </div>
        <%= link_to "See Post", user_post_path(post.user, post), class: "btn" %>
    </div>
</section>

app/views/posts/_user_cards.hmtl.erb
<section class='user-section-card'>
<div class="user-img">
    <%= image_tag('user-img.png',  :width => "100px", :heigth=>"100px") %>
</div>

<div class="user-section-card">
    <div class="user-details">
        <h2> <%= @posts.first.user.name %> </h2>
    </div>
<div class="user-card">
    <p class="number-posts" >
        Number of posts:<%= @posts.first.user.posts_counter  %>
    </p>  
</div>
</section>

app/views/posts/index.html.erb
<section class="users">
<% if @posts.exists? %>
      <%= render partial: "user_posts", locals: { post: @posts.first.user } %>
    <% @posts.each do |post|  %>
    <div>
        <%= render partial: "post_cards", locals: { post: post } %> 
    </div>
    <% end %>
<% else %>
    <p>No posts found for this user</p>
<% end %>
</section>

app/views/posts/new.html.erb
<h2>Create a new post</h2>
<%= form_with model: @post, url: user_posts_path, method: :post do |form| %>

  <div>
    <%= form.label :title, class: "small-label" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text, class: "small-label" %>
    <%= form.text_area :text, size: "70x5"  %>
  </div>

  <div>
    <%= form.submit "Create Post", class: "btn" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="users">
        <div class="user-section-card">
            <h2><%= @post.title %> by <%= @post.user.name %> </h2>
            <p>Comments: <%= @post.comments_counter %></p>
            <p>Likes: <%= @post.likes_counter %></p>
            <% if can? :destroy, @post  %>
            <%= button_to 'Delete', user_post_path(@post.user.id, @post.id), method: :delete, class: 'btn btn-danger' %> 
        <% end %>
        </div> 
        <div class="user-section-card">
            <h4><%= @post.text %></h4>
            <%= render partial: "likes/new_like"%>
        </div>
        <div class="commets-container">
            <%= render partial: "comment_card", locals: { post: @post, comments: @post.comment} %>
            <%= render partial: "comments/new_comment"%>
        </div>

</div> 